
export type ThemeColors = {
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  onSurface: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  shadow: string;
  scrim: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  primaryFixed: string;
  onPrimaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixedVariant: string;
  secondaryFixed: string;
  onSecondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixedVariant: string;
  tertiaryFixed: string;
  onTertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixedVariant: string;
  surface1: string;
  surface2: string;
  surface3: string;
  text: string;
  textMuted: string;
  accent: string;
  onAccent: string;
  muted: string;
  destructive: string;
  onDestructive: string;
  errorColor: string;
  success: string;
  warning: string;
  border: string;
  focusBorder: string;
  input: string;
  tint: string;
  selected: string;
};

export type ThemeMode = "light" | "dark";

const light: ThemeColors = {
  primary: "#BD580F",
  onPrimary: "#FFFFFF",
  primaryContainer: "#F7E3D4",
  onPrimaryContainer: "#2B1708",
  secondary: "#3B9153",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#DDEEE2",
  onSecondaryContainer: "#112216",
  tertiary: "#B71567",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#F6D5E6",
  onTertiaryContainer: "#2A091A",
  error: "#C60618",
  onError: "#FFFFFF",
  errorContainer: "#F9D2D6",
  onErrorContainer: "#2D060A",
  background: "#FAFAFA",
  onBackground: "#18181B",
  surface: "#FAFAFA",
  onSurface: "#18181B",
  surfaceVariant: "#E4E3E8",
  onSurfaceVariant: "#484653",
  outline: "#78728D",
  outlineVariant: "#C9C8D0",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#303036",
  inverseOnSurface: "#F2F2F3",
  inversePrimary: "#F2C6A6",
  surfaceDim: "#DCDCE0",
  surfaceBright: "#FAFAFA",
  surfaceContainerLowest: "#FFFFFF",
  surfaceContainerLow: "#F4F4F5",
  surfaceContainer: "#EFEFF1",
  surfaceContainerHigh: "#EAE9EC",
  surfaceContainerHighest: "#E4E4E7",
  primaryFixed: "#F7E3D4",
  onPrimaryFixed: "#2B1708",
  primaryFixedDim: "#F2C6A6",
  onPrimaryFixedVariant: "#894210",
  secondaryFixed: "#DDEEE2",
  onSecondaryFixed: "#112216",
  secondaryFixedDim: "#B9DFC4",
  onSecondaryFixedVariant: "#2E6B3F",
  tertiaryFixed: "#F6D5E6",
  onTertiaryFixed: "#2A091A",
  tertiaryFixedDim: "#EFA9CC",
  onTertiaryFixedVariant: "#85144D",
  surface1: "#EFEFF1",
  surface2: "#EAE9EC",
  surface3: "#E4E4E7",
  text: "#18181B",
  textMuted: "#484653",
  accent: "#B71567",
  onAccent: "#FFFFFF",
  muted: "#EFEFF1",
  destructive: "#C60618",
  onDestructive: "#FFFFFF",
  errorColor: "#C60618",
  success: "#3B9153",
  warning: "#F6D5E6",
  border: "#C9C8D0",
  focusBorder: "#BD580F",
  input: "#EAE9EC",
  tint: "#BD580F",
  selected: "#BD580F26",
};

const dark: ThemeColors = {
  primary: "#F2C6A6",
  onPrimary: "#592D0D",
  primaryContainer: "#894210",
  onPrimaryContainer: "#F7E3D4",
  secondary: "#B9DFC4",
  onSecondary: "#20462B",
  secondaryContainer: "#2E6B3F",
  onSecondaryContainer: "#DDEEE2",
  tertiary: "#EFA9CC",
  onTertiary: "#561033",
  tertiaryContainer: "#85144D",
  onTertiaryContainer: "#F6D5E6",
  error: "#F6A2AA",
  onError: "#5D0911",
  errorContainer: "#900916",
  onErrorContainer: "#F9D2D6",
  background: "#0F0E10",
  onBackground: "#E4E4E7",
  surface: "#0F0E10",
  onSurface: "#E4E4E7",
  surfaceVariant: "#484653",
  onSurfaceVariant: "#C9C8D0",
  outline: "#938FA3",
  outlineVariant: "#484653",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#E4E4E7",
  inverseOnSurface: "#303036",
  inversePrimary: "#BD580F",
  surfaceDim: "#0F0E10",
  surfaceBright: "#3A3941",
  surfaceContainerLowest: "#0A0A0B",
  surfaceContainerLow: "#18181B",
  surfaceContainer: "#1D1D20",
  surfaceContainerHigh: "#29292E",
  surfaceContainerHighest: "#35343C",
  primaryFixed: "#F7E3D4",
  onPrimaryFixed: "#2B1708",
  primaryFixedDim: "#F2C6A6",
  onPrimaryFixedVariant: "#894210",
  secondaryFixed: "#DDEEE2",
  onSecondaryFixed: "#112216",
  secondaryFixedDim: "#B9DFC4",
  onSecondaryFixedVariant: "#2E6B3F",
  tertiaryFixed: "#F6D5E6",
  onTertiaryFixed: "#2A091A",
  tertiaryFixedDim: "#EFA9CC",
  onTertiaryFixedVariant: "#85144D",
  surface1: "#1D1D20",
  surface2: "#29292E",
  surface3: "#35343C",
  text: "#E4E4E7",
  textMuted: "#C9C8D0",
  accent: "#EFA9CC",
  onAccent: "#561033",
  muted: "#1D1D20",
  destructive: "#F6A2AA",
  onDestructive: "#5D0911",
  errorColor: "#F6A2AA",
  success: "#B9DFC4",
  warning: "#85144D",
  border: "#484653",
  focusBorder: "#F2C6A6",
  input: "#29292E",
  tint: "#F2C6A6",
  selected: "#F2C6A633",
};

export const COLOR_THEMES: Record<ThemeMode, ThemeColors> = {
  light,
  dark,
};
